POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"Async awaiting intensifies",
    "author": "ObiOne",
    "url":"https://dnnotes-netlify.app",
    "likes": 322,
    "user": "5f04ea55c184a644d8489c52"
}